default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: detect-private-key
    - id: check-ast
  
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

